version: '3.7'

services:
  service-firsname:
    container_name: FirstName
    image: service-firsname:v1
    build: ./DockerSBServise_FirstName/
    ports:
      - '8083:8080'
    depends_on:
      - my-sql-db
     
      
  service-lastname:
    container_name: LastName
    image: service-lastname:v1
    build: ./DockerSBServise_LastName/
    ports:
      - '8082:8080'
    depends_on:
      - service-firsname
    
  service-age:
    container_name: Age
    image: service-age:v1
    build: ./DockerSBServise_Age
    ports:
      - '8081:8080'
    depends_on:
      - service-lastname 
    
  my-sql-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'Docker_DB'
      MYSQL_USER: 'DockerUser'
      MYSQL_PASSWORD: 'UserPass'
      MYSQL_ROOT_PASSWORD: 'rootPass'
    container_name: db_mysql
    ports:
      - '3308:3306'
    volumes:
      - /home/mydocker/mysql:/var/lib/mysql
    